import type { LayoutTable } from "../types.ts";

export const qwerty: LayoutTable = {
  id: "qwerty",
  label: "QWERTY (US)",
  keyToChar: {
    Backquote: { lower: "`", shift: "~" },
    Digit1: { lower: "1", shift: "!" },
    Digit2: { lower: "2", shift: "@" },
    Digit3: { lower: "3", shift: "#" },
    Digit4: { lower: "4", shift: "$" },
    Digit5: { lower: "5", shift: "%" },
    Digit6: { lower: "6", shift: "^" },
    Digit7: { lower: "7", shift: "&" },
    Digit8: { lower: "8", shift: "*" },
    Digit9: { lower: "9", shift: "(" },
    Digit0: { lower: "0", shift: ")" },
    Minus: { lower: "-", shift: "_" },
    Equal: { lower: "=", shift: "+" },

    KeyQ: { lower: "q", shift: "Q" },
    KeyW: { lower: "w", shift: "W" },
    KeyE: { lower: "e", shift: "E" },
    KeyR: { lower: "r", shift: "R" },
    KeyT: { lower: "t", shift: "T" },
    KeyY: { lower: "y", shift: "Y" },
    KeyU: { lower: "u", shift: "U" },
    KeyI: { lower: "i", shift: "I" },
    KeyO: { lower: "o", shift: "O" },
    KeyP: { lower: "p", shift: "P" },
    BracketLeft: { lower: "[", shift: "{" },
    BracketRight: { lower: "]", shift: "}" },
    Backslash: { lower: "\\", shift: "|" },

    KeyA: { lower: "a", shift: "A" },
    KeyS: { lower: "s", shift: "S" },
    KeyD: { lower: "d", shift: "D" },
    KeyF: { lower: "f", shift: "F" },
    KeyG: { lower: "g", shift: "G" },
    KeyH: { lower: "h", shift: "H" },
    KeyJ: { lower: "j", shift: "J" },
    KeyK: { lower: "k", shift: "K" },
    KeyL: { lower: "l", shift: "L" },
    Semicolon: { lower: ";", shift: ":" },
    Quote: { lower: "'", shift: '"' },

    KeyZ: { lower: "z", shift: "Z" },
    KeyX: { lower: "x", shift: "X" },
    KeyC: { lower: "c", shift: "C" },
    KeyV: { lower: "v", shift: "V" },
    KeyB: { lower: "b", shift: "B" },
    KeyN: { lower: "n", shift: "N" },
    KeyM: { lower: "m", shift: "M" },
    Comma: { lower: ",", shift: "<" },
    Period: { lower: ".", shift: ">" },
    Slash: { lower: "/", shift: "?" },
  },
};
